# This is the name of the workflow, visible on GitHub UI
name: Test Library's Examples
on:
  push: # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    paths:
      - '**.ino'
      - '**.cpp'
      - '**.h'
      - '**LibraryBuild.yml'
  pull_request:

jobs:
  build:
    name: ${{ matrix.mcu }} - test compiling examples

    # Target OS
    runs-on: ubuntu-20.04

    env:
      # Comma separated list without double quotes around the list
      REQUIRED_LIBRARIES: ESP Logger

    strategy:
      # The Matrix contains all the configuration to be tested. For each configuration, all the examples are tested
      matrix:

        # A couple of configuration for testing the library
        mcu:
          - esp8266
          - esp32

        # define all the parameters needed to compile the sketches
        include:

          # read the following block like:
          # if in current configuration the parameter "board-type" is equal to "esp8266",
          # add the following parameters to this configuration
          - board-type: esp8266
            platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
            # You can only state specific version, no semantic version rules
            arduino-platform: esp8266:esp8266@2.7.4
            # In arduino-boards-fqbn you can specify additional hardware parameters,
            # like clock frequency or partition scheme
            # Type "arduino-cli board listall" to view the available boards
            arduino-boards-fqbn: esp8266:esp8266:generic

          - board-type: esp32
            platform-url: https://dl.espressif.com/dl/package_esp32_index.json
            arduino-platform: esp32:esp32@1.0.5
            arduino-boards-fqbn: esp32:esp32:esp32

      # Do not cancel all jobs / architectures if one job fails
      fail-fast: false

    # This is the list of steps this job will run
    steps:

      # clone the repo using the `checkout` action
      - name: Checkout
        uses: actions/checkout@v2

      - name: Arduino Lint
        uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update

      - name: Compile all examples using the arduino-test-compile action
        uses: ArminJo/arduino-test-compile@master
        with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          arduino-platform: ${{ matrix.arduino-platform }}
          platform-url: ${{ matrix.platform-url }}
          required-libraries: ${{ env.REQUIRED_LIBRARIES }}
          sketches-exclude: ${{ matrix.sketches-exclude }}
          build-properties: ${{ toJson(matrix.build-properties) }}
